[package]
name = "pwdgen"
version = "0.1.0"
authors = ["Jesse Stricker"]
edition = "2021"
rust-version = "1.64"
description = "A simple password generator for the command line."
license = "Apache-2.0"
publish = false

[[bin]]
name = "pwdgen"
